source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '6.0'

pod 'XAspect-Foundation_UnicodifyingDescriptionsOfObjects/All', :path => './../'

target :Foundation_UnicodifyingDescriptionsOfObjectsDevTests do
  pod 'XLTestLog', '~> 1.0'
end