source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '6.0'

pod 'Foundation_UnicodifyingDescriptionsOfObjects', :path => './../'

target :Foundation_UnicodifyingDescriptionsOfObjectsDevTests do
 pod 'Foundation_UnicodifyingDescriptionsOfObjects', :path => './../'
end